name: 'example'
description: 'Example app for the JsonDynamicWidget library'
publish_to: 'none'
version: '1.0.0+26'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  desktop_window: '^0.4.0'
  dotted_border: '^2.0.0+3'
  flutter:
    sdk: 'flutter'
  flutter_svg: '^1.1.6'
  json_dynamic_widget:
    path: '../'
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.17
  fluttertoast: ^8.1.2
  material_dialogs: ^1.1.4
  nb_utils: ^4.6.25
  syncfusion_flutter_charts: ^20.4.44
  google_maps_flutter: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: 'flutter'

flutter:
  uses-material-design: true
  assets:
    - 'assets/images/'
    - 'assets/pages/'
    - 'assets/secrets/'
    - 'assets/widgets/'
  fonts:
    - family: 'lato'
      fonts:
        - asset: 'assets/fonts/Lato-Regular.ttf'

    - family: 'metal'
      fonts:
        - asset: 'assets/fonts/MetalMania-Regular.ttf'

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
